name: Hessambetbot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pillow
        run: pip install Pillow

      - name: Run bot
        run: python bot.py
